### ISSUE TITLE
only one throw 

### ISSUE THREAD

**Issue by Chriskimm1** [Chriskimm1/Phaser-Plane-Game#4]
@WilliamfShaw 
### Context

When submitting an issue provide some context as to what the problem is. This includes but is not limited to:
- What User Story you are currently working on
  want to shoot mutiple ninja stars 
- What you are trying to do
  throw more than one 
- Detailed description of the bug or error
  when i throw one and try to throw the second one it says undefined
### What have you tried?

Give information about what you have done to solve the problem. Including but not limited to:
- Documentation you have looked at
  ive tried looking at the phaser space invader example 
- Steps you have taken to solve the problem
  looked at different ways to create the ninja stars 
- Resources you have used
  phaser and forums and youtube
### Question

What would you like help with specifically?
creating more than one ninja stars

```
   shuriken = game.add.group();
    shuriken.enableBody = true;
    shuriken.physicsBodyType = Phaser.Physics.ARCADE;
    shuriken.createMultiple(30, 'shuriken'); < --- doesnt this make multiple shurikens ? 
    shuriken.setAll('anchor.x', 0.5);
    shuriken.setAll('anchor.y', 1);
    shuriken.setAll('outOfBoundsKill', true);
    shuriken.setAll('checkWorldBounds', true);


}
```

**Comment by WilliamfShaw** [comment]
@Chriskimm1 
Kewl, 

 I cant do anything with this at all. I have no idea whats going on. 

https://github.com/ga-students/WDI_McClane/blob/master/project_02/asking_for_help.md

Fill that out and then lets tackle it

**Comment by WilliamfShaw** [comment]
@Chriskimm1 can you please close this issue
