### ISSUE TITLE
need help 

### ISSUE THREAD

**Issue by Chriskimm1** [Chriskimm1/Phaser-Plane-Game#5]
## CONTEXT

@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284
##### WHAT USER STORY YOU ARE WORKING ON:

i want to have a button where i can start the game 
##### WHAT YOU ARE TRYING TO DO:

i have a seperate page thats linked in index to call startGame via jquery
##### DETAILED DESCRIPTION OF THE BUG/ERROR:

``` $(function(){
    $("#button").on("click", startGame);
});
```

and also having problems doing kill animation doing same code as killing enemy and tried even putting a loop and timer and kill all doesnt work.

many many problems 

```
function killPlayer(player){
    player.animations.add("dead", [15], 1);
    player.animations.play("dead", 1, false, true);
}
## WHAT I'VE TRIED
ive tried double checking if my jquery is wrong and also tried switching out the min.js
also tried console logging a function nothing shows up 

```

**Comment by WilliamfShaw** [comment]
@Chriskimm1 where do you stand on this issue?
